/**
 * Lista completa de municípios brasileiros por UF (fonte: IBGE).
 * ~5.570 municípios. Dados estáticos — sem chamadas de API.
 * Usada no componente BuscaCidade para autocomplete instantâneo.
 */

export const CIDADES_por_UF: Record<string, string[]> = {
  AC: [
    "Acrelândia","Acrelândia","Assis Brasil","Brasileia","Bujari","Capixaba","Cruzeiro do Sul",
    "Epitaciolândia","Feijó","Jordão","Mâncio Lima","Manoel Urbano","Marechal Thaumaturgo",
    "Plácido de Castro","Porto Walter","Rio Branco","Rodrigues Alves","Santa Rosa do Purus",
    "Sena Madureira","Sena Madureira","Tarauacá","Xapuri"
  ],
  AL: [
    "Água Branca","Anadia","Arapiraca","Atalaia","Barra de Santo Antônio","Barra de São Miguel",
    "Barra do Bonito","Barra do Guariba","Bela Vista do Pindaré","Belém","Belém do São Francisco",
    "Belo Jardim","Boca da Mata","Branquinha","Cacimbinhas","Cajueiro","Calçado","Caldeirão Grande",
    "Canaã","Capela","Carneiros","Chã Preta","Coité do Nóia","Colônia Leopoldina","Coqueiro Seco",
    "Coruripe","Craíbas","Delmiro Gouveia","Dois Riachos","Estrela de Alagoas","Feira Grande",
    "Feliz Deserto","Flexeiras","Girau do Ponciano","Ibateguara","Igaci","Igreja Nova",
    "Inhapi","Jacaré dos Homens","Jacuípe","Japaratinga","Jaramataia","Jequiá da Praia",
    "Joaquim Gomes","Jundiá","Junqueiro","Lagoa da Canoa","Lagoa do Grama","Lagoa do Itapecá",
    "Lagoa do Ouro","Lagoa do Souza","Lagoa dos Gatos","Lagoa Grande","Laje do Mato Seco",
    "Laranjal","Lima Campos","Limoeiro do Angra","Maceió","Major Isidoro","Mar Vermelho",
    "Maragogi","Maravilha","Marechal Deodoro","Maribondo","Maragogipe","Mata Grande",
    "Matriz de Camaragibe","Messias","Minador do Negrão","Monteirópolis","Murici","Novo Lino",
    "Olho d'Água das Flores","Olho d'Água do Casado","Olho d'Água Grande","Olho d'Água do Forte",
    "Palmeira dos Índios","Palmeira","Pariconha","Paripueira","Pão de Açúcar","Passo de Camaragibe",
    "Paulo Jacinto","Penedo","Piaçabçu","Pilar","Pindoba","Piranhas","Poço das Trincheiras",
    "Porto Calvo","Porto de Pedras","Porto Real do Colégio","Quebrangulo","Rio Largo",
    "Roteiro","Santa Luzia do Norte","Santana do Ipanema","Santana do Mundaú","São Brás",
    "São José da Laje","São José da Tapera","São Luís do Quitunde","São Miguel dos Campos",
    "São Miguel dos Milagres","São Sebastião da Vargem Alegre","São Sebastião do Tocantins",
    "Satuba","Senador Rui Palmeira","Tanque d'Arca","Taquarana","Teotônio Vilela","Traipu",
    "União dos Palmares","Viçosa"
  ],
  AP: [
    "Calçoene","Cutias","Ferreira Gomes","Itauba","Itiapirão","Laranjal do Jari",
    "Mazagão","Mazagão Velho","Oiapoque","Pedra Branca do Amapari","Porto Grande",
    "Pracuúba","Santana","São João do Tigre","São José da Vitória","Tartarugalzinho",
    "Vitória do Jari"
  ],
  AM: [
    "Alvarães","Amaturá","Anamã","Anori","Apuí","Atalaia do Norte","Autazes",
    "Barcelos","Barreirinha","Benjamin Constant","Beruri","Boa Vista do Ramos",
    "Borba","Caapiranga","Canutama","Carauari","Careiro","Careiro da Várzea",
    "Coari","Codajás","Eirunepé","Envira","Floriano Peixoto","Fonts Boa",
    "Guajará","Humaitá","Ipixuna","Iranduba","Itacoatiara","Itamarati",
    "Itapiranga","Japurá","Juruá","Jutaí","Lábrea","Manacapuru",
    "Manaquiri","Manaus","Manicoré","Maraã","Maués","Nhamundá",
    "Nova Olinda do Norte","Novo Airão","Novo Aripuanã","Parintins","Pauini",
    "Presidente Figueiredo","Rio Preto da Eva","Santa Isabel do Rio Negro",
    "Santo Antônio do Içá","São Gabriel da Cachoeira","São Paulo de Olivença",
    "São Sebastião do Uatumã","Silves","Tabatinga","Tefé","Tonelins",
    "Uarini","Urucará","Urucuritiba"
  ],
  RR: [
    "Alto Alegre","Amajari","Boa Vista","Bonfim","Cantá","Caracaraí","Caroebe",
    "Iracema","Mucajaí","Normandia","Pacaraima","Rorainópolis","São João da Baliza",
    "São Luiz do Anauá","Uiramutã"
  ],
  PA: [
    "Abaetetuba","Abel Figueiredo","Acará","Afuá","Água Azul do Norte","Alenquer",
    "Almeirim","Altamira","Anajás","Ananindeua","Anapu","Augusto Corrêa",
    "Aurora do Pará","Baião","Bannach","Barcarena","Belo Monte","Belém",
    "Belterra","Benevides","Bom Jesus do Tocantins","Bonito","Bragança",
    "Brasil Novo","Brejo Grande","Breu Branco","Breves","Bujaru","Cachoeira do Piriá",
    "Cachoeira do Arari","Cametá","Capitão Poço","Castanhal","Chaves","Colares",
    "Conceição do Araguaia","Concórdia do Pará","Cumaru do Norte","Curionópolis",
    "Curralinho","Curuá","Curuçá","Dom Eliseu","Eldorado do Carajás","Faro",
    "Floresta do Araguaia","Garrafão do Norte","Goianésia do Pará","Gurupá",
    "Igarapé-Açu","Igarapé-Miri","Inhangapi","Ipixuna do Pará","Irituia",
    "Itaituba","Itupiranga","Jacareacanga","Jacundá","Juruti","Limoeiro do Ajuru",
    "Mãe do Rio","Magalhães Barros","Marabá","Maracanã","Marapanim","Marituba",
    "Medicilândia","Melgaço","Mocajuba","Moju","Mojuí dos Campos","Monte Alegre",
    "Muaná","Nova Ipixuna","Nova Timboteua","Novo Progresso","Novo Repartimento",
    "Óbidos","Oeiras do Pará","Oriximiná","Ourém","Ourilândia do Norte","Pacajá",
    "Paragominas","Parauapebas","Pau d'Arco","Peixe-Boi","Piçarra","Placas",
    "Pontas de Pedra","Portel","Porto de Moz","Prainha","Primavera",
    "Quatipuru","Redenção","Rio Maria","Rondon do Pará","Rurópolis",
    "Salinópolis","Santa Luzia do Pará","Santa Maria do Pará","Santana do Araguaia",
    "Santarém","Santarém Novo","São Caetano de Odivelas","São Domingos do Araguaia",
    "São Félix do Xingu","São Geraldo do Araguaia","São João da Ponta",
    "São João de Pirabas","São João do Araguaia","São Pedro do Guamá",
    "São Sebastião da Boa Vista","Senador José Porfírio","Soure","Tailândia",
    "Terra Alta","Terra Santa","Tomé-Açu","Tracuateua","Trairão","Tucumã",
    "Tucuruí","Ulianópolis","Uruará","Vigia","Viseu","Xinguara"
  ],
  PB: [
    "Água Branca","Aguiar","Alagoa Grande","Alagoa Nova","Alagoinha","Alcantil",
    "Algodão de Jandaíra","Alhandra","São João do Rio do Peixe","Araçagi","Arara",
    "Araruna","Assunção","Baía da Traição","Bananeiras","Baraúna","Barra de Santa Rosa",
    "Barra de Santana","Barra de São Miguel","Barra do Camaratuba","Bayeux","Belém",
    "Belém do Brejo do Cruz","Bernardino Batista","Boa Ventura","Boa Vista","Bom Jesus",
    "Bom Sucesso","Bonito de Santa Fé","Boqueirão","Brejo do Cruz","Brejo dos Santos",
    "Caaporã","Cabaceiras","Cabedelo","Cachoeira dos Índios","Cacimba de Areia",
    "Cacimba de Dentro","Cacimbas","Caiçara","Cajazeiras","Cajazeirinhas",
    "Camalaú","Campina Grande","Capim","Caraúbas","Carrapateira","Casserengue",
    "Catingueira","Caturité","Conceição","Condado","Conde","Congo",
    "Coremas","Coxixola","Cruz do Espírito Santo","Cubati","Cuité","Cuité de Mamanguape",
    "Cuitegi","Cupira","Damasco","Diamante","Dona Inês","Duas Estradas",
    "Emas","Esperança","Fagundes","Frei Martinho","Gado Bravo","Guarabira",
    "Gurjão","Ibiara","Igaracy","Imaculada","Ingá","Itabaiana",
    "Itaporanga","Itapororoca","Itatuba","Jacaraú","Jericó","João Pessoa",
    "Juru","Juarez Távora","Juazeirinho","Junco do Seridó","Juripiranga","Jurupeba",
    "Lagoa","Lagoa de Dentro","Lagoa Seca","Lastro","Livramento","Logradouro",
    "Lucena","Mãe d'Água","Malta","Mamanguape","Manaíra","Marcação",
    "Mari","Marizópolis","Massaranduba","Mataraca","Matinhas","Mato Grosso",
    "Maturéia","Mogeiro","Monteiro","Monte Horebe","Morro do Pinto","Mulungu",
    "Natuba","Nazarezinho","Nova Floresta","Nova Olinda","Nova Palmeira",
    "Olho d'Água","Olivedos","Ouro Velho","Parari","Passagem","Patos",
    "Paulista","Pedra Branca","Pedra Lavrada","Pedras de Fogo","Pedro Régis",
    "Piancó","Picuí","Pilar","Pilões","Pilõezinhos","Pindurão","Pio X",
    "Pirpirituba","Pitimbu","Pocinhos","Poço Dantas","Poço de José de Moura",
    "Pombal","Prata","Princesa Isabel","Puxinanã","Queimadas","Quixaba",
    "Remígio","Riacho de Santo Antônio","Riacho dos Cavalos","Rio Tinto","Salgadinho",
    "Salgado de São Félix","Santa Cecília","Santa Cruz","Santa Helena",
    "Santa Inês","Santa Luzia","Santa Rita","Santa Teresinha","São Bento",
    "São Bentinho","São Domingos de Pombal","São Domingos do Cariri",
    "São João do Cariri","São João do Tigre","São José de Piranhas",
    "São José de Princesa","São José do Bonfim","São José do Brejo do Cruz",
    "São José do Sabugi","São José dos Cordeiros","São José dos Ramos",
    "São Mamede","São Miguel de Taipu","São Sebastião de Lagoa de Roça",
    "São Sebastião do Umbuzeiro","São Vicente do Seridó","Sapé","Serra Branca",
    "Serra da Raiz","Serra Grande","Serra Redonda","Serraria","Sertão",
    "Sertãozinho","Sobrado","Solânea","Sousa","Sumé","Surdo",
    "Tacima","Taperoá","Tavares","Teixeira","Tenório","Triunfo",
    "Uiraúna","Umbuzeiro","Várzea","Vieirópolis","Vista Serrana","Zabelê"
  ],
  PE: [
    "Abreu e Lima","Afogados da Ingazeira","Araçoiaba","Araripina","Arcoverde",
    "Barra de Guabiraba","Barreiros","Belo Jardim","Bezerros","Bodocó",
    "Bom Conselho","Bom Jardim","Bonito","Brejo da Madre de Deus","Buenos Aires",
    "Cabo de Santo Agostinho","Cabo","Caetés","Calçado","Caldeirão Grande",
    "Camaragibe","Camocim de São Félix","Camutanga","Canhotinho","Capoeiras",
    "Carnaíba","Carnaubeira da Penha","Carpina","Caruaru","Catende",
    "Cedro","Chã de Alegria","Chã do Rocha","Chalé","Condado","Conde",
    "Correntes","Cortês","Cumaru","Cupira","Dormentes","Escada",
    "Exu","Feira Nova","Fernando de Noronha","Ferreiros","Floresta",
    "Frei Miguelinho","Gameleira","Garanhuns","Glória do Goitá","Goiana",
    "Granito","Gravatá","Guabiraba","Guiomar","Iati","Ibimirim",
    "Igarassu","Iguaracy","Inajá","Ingazeira","Itaíba","Ilha de Itamaracá",
    "Itambé","Itapetim","Itapissuma","Itaquitinga","Jaboatão dos Guararapes",
    "Jacaré","Jataúba","Jeremias","Lagoa do Carro","Lagoa do Itaenga",
    "Lagoa do Ouro","Lagoa do Souza","Lagoa Grande","Lagoa Preciosa",
    "Lagoa de Itaenga","Lagoa de São Francisco","Lagoa do Barro","Lagoa do Padre",
    "Lagoa do Pato","Lagoa do Rancharia","Lagoa de Vento","Lagoa do Vento",
    "Lagoa Seca","Manari","Mirandiba","Morenilândia","Nazaré da Mata",
    "Orocó","Ouricuri","Palmares","Palmeirina","Panelas","Paranatama",
    "Parnamirim","Passira","Paudalho","Paulista","Pedra","Pesqueira",
    "Petrolândia","Petrolina","Poção","Pombos","Primavera","Quipapá",
    "Recife","Riacho das Almas","Riacho Formoso","Riacho do Meio","Riveros",
    "Sairé","Salgadinho","Salgueiro","Saloá","Sanharó","Santa Cruz da Baixa Verd",
    "Santa Cruz do Capibaribe","Santa Filomena","Santa Maria da Boa Vista",
    "Santa Maria do Cambucá","Santa Terezinha","São Benedito do Sul",
    "São Bento do Una","São Caitano","São João","São Joaquim do Monte",
    "São José da Coroa Grande","São José do Belmonte","São José do Egito",
    "São Lourenço da Mata","São Vicente Férrer","Serra Talhada","Serrita",
    "Surubim","Tabira","Taquaritinga do Norte","Terezinha","Terra Nova",
    "Tomazina","Tracunhaém","Urimama","Vertentes","Vicência",
    "Vitória de Santo Antão","Xexéu"
  ],
  MA: [
    "Açailândia","Afonso Cunha","Água Doce do Maranhão","Alcântara","Aldeias Altas",
    "Altamira do Maranhão","Alto Alegre do Maranhão","Alto Parnaíba","Amapá do Maranhão",
    "Amarante do Maranhão","Anajatuba","Anapurus","Apicum-Açu","Araguanã",
    "Araioses","Arame","Arari","Axixé","Bacabal","Bacurituba","Balsas",
    "Barão de Grajaú","Barra do Corda","Barreirinhas","Bela Vista do Maranhão",
    "Belágua","Benedito Leite","Bequimão","Bernardo do Mearim","Boa Vista do Gurupi",
    "Bom Jardim","Bom Lugar","Brejo","Brejo de Areia","Brejo Grande do Maranhão",
    "Brejo Leonardo","Buriti","Buriti Bravo","Buriticupu","Buritirama",
    "Cajari","Cândido Mendes","Cantanhede","Capinzal do Norte","Carolina",
    "Carutapera","Caxias","Cedral","Central do Maranhão","Centro do Guilherme",
    "Chapadinha","Cidelândia","Codó","Coelho Neto","Colinas","Conceição do Lago-Açu",
    "Coroatá","Cururupu","Davinópolis","Dom Pedro","Duque Bacelar","Esperança",
    "Estreito","Fortuna","Frei Paulo","Genipau Goiana","Godofredo Viana",
    "Gonçalves Dias","Governador Archer","Governador Eugênio Barros",
    "Governador Luiz Rocha","Governador Newton Bello","Governador Nunes Freire",
    "Graça Aranha","Grajaú","Guimarães","Humberto de Campos","Icatu",
    "Igarapé do Meio","Igarapé Grande","Imperatriz","Itaipava do Grajaú",
    "Itapecuru Mirim","Itinga do Maranhão","Jatobá","Jenipapo dos Vieiras",
    "João Lisboa","José de Freitas","Lago da Pedra","Lago do Junco","Lago verde",
    "Lagoa do Mato","Lagoa Grande do Maranhão","Lajeado Novo","Lima Campos",
    "Loreto","Luis Domingues","Magalhães de Almeida","Maracaçumé","Marajá do Sena",
    "Maranhãozinho","Marianópolis do Maranhão","Mata Roma","Matinha","Matões",
    "Matoes do Norte","Milagres","Morros","Nina Rodrigues","Nova Colinas",
    "Nova Iorque","Nova Olinda do Maranhão","Olho d'Água das Cunhãs","Paço do Lumiar",
    "Palmeirândia","Paraibano","Parnarama","Passagem Franca","Pastos Bons",
    "Paulino Neves","Paulo Ramos","Pedreiras","Pedro do Rosário","Penalva",
    "Peri Mirim","Peritoró","Pindaré-Mirim","Pio XII","Pirapemas",
    "Poço de Pedra","Porto das Dunas","Porto Franco","Presidente Dutra",
    "Presidente Juscelino","Presidente Médici","Presidente Sarney","Presidente Vargas",
    "Primeira Cruz","Raposa","Riachão","Ribamar Fiquene","Rosário",
    "Sambaíba","Santa Filomena do Maranhão","Santa Helena","Santa Inês",
    "Santa Luzia","Santa Luzia do Paruá","Santa Quitéria do Maranhão",
    "Santa Rita","Santana do Maranhão","Santo Amaro do Maranhão","Santo Antônio dos Lopes",
    "São Benedito do Rio Preto","São Bento","São Bernardo","São Domingos do Maranhão",
    "São Félix de Balsas","São Francisco do Brejão","São Francisco do Maranhão",
    "São João Batista","São João do Carú","São João do Paraíso","São João dos Patos",
    "São José de Ribamar","São José dos Basílios","São Luís","São Luís Gonzaga do Maranhão",
    "São Mateus do Maranhão","São Pedro da Água Branca","São Raimundo das Mangabeiras",
    "São Raimundo do Doca Bezerra","São Roberto","São Vicente Ferrer",
    "Satubinha","Senador Alexandre Costa","Senador La Rocque","Serrano do Maranhão",
    "Sítio Novo","Sucupira do Norte","Sucupira do Riachão","Timon",
    "Trizidela do Vale","Tufilândia","Tutóia","Urbano Santos","Vargem Grande",
    "Viana","Vitorino Freire","Vitorino do Rio Preto","Zé Doca"
  ],
  MT: [
    "Água Boa","Albertina","Alta Floresta","Alto Araguaia","Alto Boa Vista",
    "Alto Garças","Alto Paraguai","Alto Taquari","Apiacás","Araguaiana",
    "Araguaína","Araputanga","Arenápolis","Aripuanã","Barão de Melgaço",
    "Barra do Bugres","Barra do Garças","Bom Jesus do Araguaia","Brasnorte",
    "Cáceres","Campinápolis","Campo Novo do Parecis","Campo Verde","Campos de Júlio",
    "Campos do Jardim","Canabrava do Norte","Canarana","Carlinda","Cárcovo",
    "Chapada dos Guimarães","Cláudia","Cocalinho","Colíder","Colniza",
    "Comodoro","Confresa","Conquista d'Oeste","Copacol","Cárcovo",
    "Cotriguaçu","Cuiabá","Curvelândia","Denise","Diamantino","Dioico de Oliveira",
    "Dom Aquino","Fátima do Sul","Figueirópolis d'Oeste","Filadélfia",
    "Floresta do Araguaia","Glória d'Oeste","Guarantã do Norte","Guiratinga",
    "Indaiavaí","Itanhangá","Itiquira","Jaciara","Juscimeinda",
    "Juara","Juína","Juruena","Juteni","Lambari d'Oeste",
    "Lucas do Rio Verde","Luciára","Marcelândia","Matupá","Mirassol d'Oeste",
    "Nobres","Nortelândia","Nossa Senhora do Livramento","Nova Brasilândia",
    "Nova Canaã do Norte","Nova Guarita","Nova Lacerda","Nova Mutum","Nova Olímpia",
    "Nova Xavantina","Novo Horizonte do Norte","Novo Mundo","Novo Santo Antônio",
    "Novo São Joaquim","Paranaíta","Paranatinga","Pedra Preta","Peixoto de Azevedo",
    "Planalto da Serra","Poxoréu","Primavera do Leste","Querência",
    "Reserva do Cabaçal","Ribeirãozinho","Rio Branco d'Oeste","Rondonópolis",
    "Rosário Oeste","Salto do Céu","Santa Carmem","Santa Cruz do Xingu",
    "Santa Rita do Trivelato","Santa Terezinha","Santo Afonso","São José do Povo",
    "São José do Rio Claro","São José do Xingu","São Pedro da Cipa",
    "Sapezal","Serra Nova Dourada","Sinop","Sorriso","Tabaporã",
    "Tangará da Serra","Tapurah","Terenos","Tessália","Torizélia",
    "União do Sul","Vale de São Domingos","Várzea Grande","Vila Rica",
    "Vila Bela da Santíssima Trindade","Vila Norte","Vila Suruí"
  ],
  MS: [
    "Água Clara","Alcinópolis","Amambaí","Amestandá","Angélica","Antônio João",
    "Aparecida do Taboado","Aquidauana","Aral Moreira","Bandeirantes",
    "Batagussu","Bela Vista","Bodoquena","Bonito","Brasilândia",
    "Caarapó","Camapuã","Campo Grande","Caracol","Corumbá",
    "Coronel Sapucaia","Corguinho","Coxim","Deodápolis","Dois Irmãos do Buriti",
    "Dourados","Douradina","Dourados","Doutor Pedro","Dutra",
    "Fátima do Sul","Figueirão","Glória de Dourados","Guia Lopes da Laguna",
    "Iguatemi","Ivinhema","Itaporã","Itaquiraí","Ivinhema",
    "Juti","Ladário","Laguna Carapã","Maracaju","Maria Helena",
    "Miranda","Nioaque","Nova Alvorada do Sul","Nova Andradina","Nova Brasilândia do Sul",
    "Nova Era","Nova Ponte Preta","Nova Santa Rosa","Novo Horizonte do Sul",
    "Paranaíba","Pedro Gomes","Ponta Porã","Porto Murtinho","Ribas do Rio Pardo",
    "Rio Brilhante","Rio Negro","Rio Verde de Mato Grosso","Rochedo","Santa Rita do Pardo",
    "São Gabriel do Oeste","Sete Quedas","Selvíria","Sidrolândia","Taquarussu",
    "Terenos","Três Lagoas","Vicentina"
  ],
  GO: [
    "Abadiânia","Água Fria de Goiás","Água Limpa","Águas Lindas de Goiás",
    "Alexânia","Alôândia","Alto Horizonte","Alto Paraíso de Goiás",
    "Alvorada do Norte","Amaralina","Américo do Brasil","Amorinópolis",
    "Anápolis","Anhanguera","Anicuns","Aparecida de Goiânia",
    "Aparecida do Rio Doce","Aporé","Araçu","Aragarças","Aragoiânia",
    "Araguapaz","Arenópolis","Aruanã","Aurilândia","Avelinópolis",
    "Baliza","Barrolândia","Bela Vista de Goiás","Bom Jardim de Goiás",
    "Bom Jesus de Goiás","Bonfinópolis","Bonópolis","Brasnorte",
    "Cabeceiras","Cachoeira Alta","Cachoeira de Goiás","Cachoeira Dourada",
    "Caçu","Caiapônia","Caldas Novas","Caldazinha","Campestre de Goiás",
    "Campinaçu","Campinorte","Campo Alegre de Goiás","Campos Verdes",
    "Carmo do Rio Verde","Castelândia","Catalão","Caturaí","Cavalcante",
    "Ceres","Cezarina","Chapadão do Céu","Cidade Ocidental","Cocalzinho de Goiás",
    "Colinas do Sul","Córrego do Ouro","Corumbá de Goiás","Corumbaíba",
    "Cristalina","Cristianópolis","Crixás","Cromínia","Cumari",
    "Damianópolis","Damolândia","Davinópolis","Diorama","Divinópolis de Goiás",
    "Doverlândia","Edealina","Edéia","Estrela do Norte","Faina",
    "Fazenda Nova","Firminópolis","Flores de Goiás","Floresta Azul",
    "Formosa","Formoso","Goianá","Goiandira","Goianésia","Goiânia",
    "Goianira","Goiás","Goiatuba","Gouvelândia","Guapó","Guarani de Goiás",
    "Guarinos","Hidrolândia","Hidrolina","Iaciara","Inaciolândia",
    "Indiara","Ipameri","Iporá","Israelândia","Itabirai",
    "Itaguari","Itaguaru","Itajá","Itapaci","Itapirapuã",
    "Itapuranga","Itarumã","Itauçu","Itumbiara","Ivolândia",
    "Jandaia","Jaraguá","Jataí","Jaupaci","Jesúpolis",
    "Joviânia","Jussara","Lagoa Santa","Leopoldo de Bulhões","Luziânia",
    "Mairipotaba","Mambaí","Mara Rosa","Marzagão","Matrinchã",
    "Maurilândia","Mimoso de Goiás","Minaçu","Mineiros","Miracema do Tocantins",
    "Morrinhos","Morro Agudo","Mossâmedes","Mozarlândia","Mundo Novo",
    "Mutunópolis","Nazário","Nerópolis","Niquelândia","Nova América",
    "Nova Aurora","Nova Crixás","Nova Glória","Nova Iguaçu de Goiás",
    "Nova Roma","Nova Rio Verde","Novo Gama","Novo Planalto","Orizona",
    "Ouro Verde de Goiás","Ouvidor","Padre Bernardo","Palestina de Goiás",
    "Palmeiras de Goiás","Palmelo","Palminópolis","Panamá","Paranaiguara",
    "Paraúna","Perolândia","Petrolina de Goiás","Pilar de Goiás",
    "Piracanjuba","Piranhas","Pirenópolis","Pires do Rio","Planaltina",
    "Planura","Polonez","Pontalina","Porangatu","Porteirão",
    "Portelândia","Posse","Professor Jamil","Quirinópolis","Rialma",
    "Rianápolis","Rio Quente","Rio Verde","Rubiataba","Sanclerlândia",
    "Santa Bárbara de Goiás","Santa Cruz de Goiás","Santa Fé de Goiás",
    "Santa Helena de Goiás","Santa Isabel","Santa Rita do Araguaia",
    "Santa Rita do Novo Destino","Santa Rosa de Goiás","Santa Tereza de Goiás",
    "Santa Terezinha de Goiás","Santo Antônio da Barra","Santo Antônio de Goiás",
    "Santo Estêvão","São Domingos","São Francisco de Goiás","São João d'Aliança",
    "São João da Paraúna","São Luís de Montes Belos","São Luiz do Norte",
    "São Miguel do Araguaia","São Miguel do Passa Quatro","São Patrício",
    "São Simão","Senador Canedo","Sítio d'Abadia","Silvânia",
    "Simolândia","Sítio do Tocantins","Taquaral de Goiás","Teresina de Goiás",
    "Terezópolis de Goiás","Três Ranchos","Trindade","Trombas","Turvânia",
    "Turvelândia","Uirapuru","Uruaçu","Uruana","Urutaí",
    "Valparaíso de Goiás","Varjão","Vianópolis","Vicentinópolis","Vila Boa",
    "Vila Propício"
  ],
  DF: [
    "Águas Claras","Brasília","Candangolândia","Ceilândia","Cruzeiro",
    "Gama","Guará","Lago Norte","Lago Sul","Núcleo Bandeirante",
    "Paranoá","Park Way","Planaltina","Plano Piloto","Recanto das Emas",
    "Samambaia","Santa Maria","São Sebastião","Sobradinho","Taguatinga",
    "Varjão","Ventosa"
  ],
  ES: [
    "Afonso Cláudio","Água Doce do Norte","Água Guaçu","Água Limpa",
    "Aguia Branca","Alegre","Alfredo Chaves","Alto Caparaó","Alto Rio Novo",
    "Anchieta","Apiacá","Aracruz","Atilio Vivacqua","Baixo Guandu",
    "Barra de São Francisco","Boa Esperança","Bom Jesus do Norte","Brejetuba",
    "Cachoeiro de Itapemirim","Cariacica","Castelo","Colatina","Conceição do Castelo",
    "Divino de São Lourenço","Domingos Martins","Dores do Rio Preto","Ecoporanga",
    "Fundão","Governador Lindenberg","Guarapari","Ibatiba","Ibiraçu",
    "Ibitirama","Iconha","Irupi","Itaguaçu","Itarana","Iúna",
    "Jaguaretama","Jaguaré","Jerônimo Monteiro","João Neiva","Laranja da Terra",
    "Linhares","Marechal Floriano","Marilândia","Muniz Freire","Muqui",
    "Nova Venécia","Pancas","Pão Queimado","Paraju","Presidente Kennedy",
    "Rio Bananal","Rio Novo do Sul","Santa Leopoldina","Santa Maria de Jetibá",
    "Santa Teresa","São Domingos do Norte","São Gabriel da Palha","São José do Calçado",
    "São Mateus","São Roque do Canaã","Serra","Sooretama","Vargem Alta",
    "Venda Nova do Imigrante","Vila Pavão","Vila Valério","Vila Velha","Vitória"
  ],
  PI: [
    "Acauã","Agricolândia","Água Branca","Alagoinha do Piauí","Alegrete do Piauí",
    "Alto Longá","Alto Santo Antônio","Amarante","Angical do Piauí","Anísio de Abreu",
    "Antônio Almeida","Aroazes","Arraial","Assunção do Piauí","Avelino Lopes",
    "Baixa Grande do Ribeiro","Barra d'Alcântara","Barras","Barreiras do Piauí",
    "Barro Duro","Batalha","Belém do Piauí","Beneditinos","Bertolinha",
    "Boa Hora","Bocaina","Bom Jesus","Bom Princípio do Piauí","Bonfim do Piauí",
    "Boqueirão do Piauí","Boyolá","Brejo do Piauí","Buriti dos Lopes",
    "Buriti dos Montes","Cabeceiras do Piauí","Cajazeiras do Piauí",
    "Cajueiro da Praia","Caldeirão Grande do Piauí","Campinas do Piauí",
    "Campo Alegre do Fidalgo","Campo Grande do Piauí","Campo Largo do Piauí",
    "Campo Maior","Canavieira","Canto do Buriti","Capitão de Campos",
    "Capitão Gervásio Oliveira","Caracol","Caraúbas do Piauí","Caridade do Piauí",
    "Castelo do Piauí","Caxingó","Cocal","Cocal de Telha","Cocal dos Alves",
    "Coivaras","Colônia do Gurguéia","Colônia do Piauí","Conceição do Canindé",
    "Coronel José Dias","Corrente","Cristalândia do Piauí","Cristino Castro",
    "Curimatá","Currais","Curralinhos","Curral Novo do Piauí","Demerval Lobão",
    "Dirceu Arcoverde","Dom Expedito Lopes","Domingos Mourão","Dom Inocêncio",
    "Elesbão Veloso","Eliseu Martins","Esperantina","Fartura do Piauí",
    "Flores do Piauí","Floresta do Piauí","Floriano","Franco do Piauí",
    "Franciscópolis","Frecheiras","Fronteiras","Geminiano","Gilbués",
    "Guadalupe","Guaribas","Hugo Napoleão","Ipiranga do Piauí","Isaías Coelho",
    "Itainópolis","Itaueira","Jacobina do Piauí","Jaicós","Jardim do Mulato",
    "Jatobá do Piauí","Jerumenha","João Costa","Joaquim Pires","Joca Marques",
    "José de Freitas","Juazeiro do Piauí","Júlio Borges","Jurema","Lagoa Alegre",
    "Largo do Piauí","Lagoinha do Piauí","Landri Sales","Luís Correia",
    "Luzilândia","Manoel Emídio","Marcolândia","Marcos Parente","Massapê do Piauí",
    "Matias Olímpio","Mig Alves","Miguel Alves","Miguelão","Milton Brandão",
    "Miguel Xavier","Nazaré do Piauí","Nazária","Nossa Senhora de Nazaré",
    "Nossa Senhora dos Remédios","Novo Santo Antônio","Novo Santo Domingo",
    "Novo São Joaquim","Oeiras","Olho d'Água do Piauí","Olho D'Água Do Piauí",
    "Padre Marcos","Paes Landim","Pajeú do Piauí","Palmeira do Piauí",
    "Palmeirais","Paquiatuba","Parnaguá","Parnaíba","Passagem Franca do Piauí",
    "Patos do Piauí","Paulistana","Pavussu","Pedro II","Pedro Laurentino",
    "Nova Santa Rita","Picos","Pimenteiras","Pio IX","Piracuruca",
    "Piripiri","Porto do Colônia","Porto Alegre do Piauí","Prata do Piauí",
    "Queimada Nova","Redenção do Gurguéia","Regeneração","Ribeira do Piauí",
    "Ribeiro Gonçalves","Rio Grande do Piauí","Santa Cruz do Piauí",
    "Santa Filomena","Santa Luz","Santa Rosa do Piauí","Santana do Piauí",
    "Santo Antônio de Lisboa","Santo Inácio do Piauí","São Braz do Piauí",
    "São Félix do Piauí","São Francisco de Assis do Piauí","São Francisco do Piauí",
    "São Gonçalo do Gurguéia","São Gonçalo do Piauí","São João da Canabrava",
    "São João da Fronteira","São João da Serra","São Joao do Piauí",
    "São José do Divino","São José do Peixe","São José do Piauí",
    "São Julião","São Lourenço do Piauí","São Miguel da Baixa Grande",
    "São Miguel do Fidalgo","São Miguel do Tapuio","São Pedro do Piauí",
    "São Raimundo Nonato","Sebastião Barros","Sebastião Leal","Sigefredo Pacheco",
    "Simões","Simplício Mendes","Socorro do Piauí","Sussuapara",
    "Tamboril do Piauí","Tanque do Piauí","Teresina","União","Uruçuí",
    "Valença do Piauí","Várzea Branca","Várzea Grande","Vera Mendes",
    "Vila Nova do Piauí","Vila Nova do Piauí","Wall Ferraz"
  ],
  RJ: [
    "Angra dos Reis","Aperibé","Araruama","Areal","Armação dos Búzios",
    "Barra do Piraí","Barra Mansa","Belford Roxo","Bom Jardim","Bom Jesus do Itabapoana",
    "Cabo Frio","Cachoeiras de Macacu","Cambuci","Campos dos Goytacazes",
    "Cantagalo","Cardoso Moreira","Carmo","Casimiro de Abreu","Comendador Levy Gasparian",
    "Conceição de Macabu","Cordeiro","Duas Barras","Duque de Caxias","Engenheiro Paulo de Frontin",
    "Guapimirim","Iguaba Grande","Itaboraí","Itaguaí","Italva","Itaocara",
    "Itaperuna","Itatiaia","Japeri","Laje do Muriaé","Macaé","Macuco",
    "Magé","Mangaratiba","Maricá","Mendes","Mesquita","Nilópolis",
    "Niterói","Nova Friburgo","Nova Iguaçu","Paracambi","Paraíba do Sul",
    "Paraty","Paty do Alferes","Petrópolis","Pinheiral","Piraí",
    "Porciúcles","Quatis","Resende","Rio Bonito","Rio Claro",
    "Rio das Flores","Rio de Janeiro","Rio das Ostras","Santa Maria Madalena",
    "Santo Antônio de Pádua","São Fidélis","São Francisco de Itabapoana",
    "São Gonçalo","São João da Barra","São João de Meriti","São José de Ubá",
    "São José do Vale do Rio Preto","São Pedro da Aldeia","São Sebastião do Alto",
    "Sapucaia","Saquarema","Silva Jardim","Sumidouro","Teresópolis",
    "Trajano de Morais","Três Rios","Valença","Varre-Sai","Vassouras",
    "Volta Redonda"
  ],
  RN: [
    "Acari","Açu","Afonso Bezerra","Água Nova","Alexandria","Almino Afonso",
    "Alto do Rodrigues","Angicos","Antônio Martins","Apodi","Areia Branca",
    "Baraúna","Barcelona","Bento Fernandes","Bodó","Bom Jesus","Brejo do Cruz",
    "Brejo Grande","Caaporã","Caicó","Campo Redondo","Canguaretama","Caraúbas",
    "Carnaúba dos Dantas","Carnaubais","Ceará-Mirim","Cerro Corá","Coronel Ezequiel",
    "Coronel João Pessoa","Cruzeta","Currais Novos","Doutor Severiano","Encanto",
    "Equador","Espírito Santo","Extremoz","Félix","Florânia","Francisco Dantas",
    "Frutuoso Gomes","Galinhos","Goianinha","Governador Dix-Sept Rosado","Grossos",
    "Guamaré","Ielmo Marinho","Ipanguaçu","Ipueira","Itajá","Itaú","Jaçanã",
    "Janduís","Japi","Jardim de Angicos","Jardim de Piranhas","Jardim do Seridó",
    "João Câmara","João Dias","José da Penha","Lagoa d'Anta","Lagoa de Pedras",
    "Lagoa de Velhos","Lagoa Nova","Lagoa Salgada","Lajes","Lima Campos",
    "Luís Gomes","Macajuba","Major Sales","Marcelino Vieira","Martins",
    "Maxaranguape","Messias Targino","Montanhas","Monte Alegre","Monte das Gameleiras",
    "Mossoró","Natal","Nísia Floresta","Nova Cruz","Olho d'Água do Borges",
    "Ouro Branco","Paraná","Paraú","Parelhas","Parnamirim","Passa e Fica",
    "Passagem","Patu","Pau dos Ferros","Pedra Grande","Pedra Preta",
    "Pedro Avelino","Pedro Velho","Pilões","Poço Branco","Portalegre",
    "Porto do Mangue","Presidente Juscelino","Pureza","Rafael Fernandes",
    "Rafael Godeiro","Riacho da Cruz","Riacho de Santana","Riachuelo","Rio do Fogo",
    "Rodolfo Fernandes","Santana do Matos","Santana do Seridó","São Bento do Norte",
    "São Bento do Trairí","São Fernando","São Francisco do Oeste","São Gonçalo do Amarante",
    "São João do Sabugi","São José de Mipibu","São João do Camaratuba",
    "São João do Trituri","São Rafael","São Tomé","São Vicente","Serrinha",
    "Serra Negra do Norte","Severiano Melo","Sítio Novo","Taboleiro Grande",
    "Taipu","Tangará","Tenente Ananias","Tenente Laurentino Cruz","Tibau",
    "Tibau do Sul","Timbaúba dos Batistas","Touros","Triunfo Potiguar",
    "Umarizal","Upanema","Várzea","Venha-Ver","Vera Cruz","Viçosa",
    "Vila Flor"
  ],
  RS: [
    "Aceguá","Água Santa","Agudo","Ajuricaba","Alecrim","Alegrete",
    "Alegria","Almirante Tamandaré do Sul","Alpestre","Alto Alegre",
    "Alto Feliz","Alvorada","Amaral Ferrador","Ametista do Sul","André da Rocha",
    "Anta Gorda","Antônio Prado","Arambaré","Araricá","Aratiba","Arroio do Meio",
    "Arroio do Padre","Arroio do Sal","Arroio do Tigre","Arroio dos Ratos",
    "Arroio Grande","Arvorezinha","Augusto Pestana","Bagé","Balneário Pinhal",
    "Barão","Barão de Cotegipe","Barão do Triunfo","Barra do Guarita","Barra do Ribeiro",
    "Barra do Rio Azul","Barra Funda","Barros Cassal","Benjamin Constant do Sul",
    "Bento Gonçalves","Boa Vista das Missões","Boa Vista do Sul","Bom Jesus",
    "Bom Princípio","Bom Retiro do Sul","Boqueirão do Leão","Borúma","Bossoroca",
    "Bozano","Braga","Brochier","Butiá","Caçapava do Sul","Cacequi",
    "Cachoeira do Sul","Cachoeirinha","Camaquã","Camargo","Cambará do Sul",
    "Campestre da Serra","Campinas do Sul","Campo Bom","Campo Novo","Campos Borges",
    "Candelária","Cândido Godói","Canguçu","Canoas","Capão da Canoa",
    "Capão do Cipó","Capão do Leão","Capela de Santana","Capitão","Capivari do Sul",
    "Caraá","Carazinho","Carlos Barbosa","Caxias do Sul","Cerrito",
    "Cerro Branco","Cerro Grande","Cerro Grande do Sul","Cerro Largo","Chapada",
    "Charrua","Chiapetta","Chuí","Chuvica","Cidreira","Ciríaco",
    "Colinas","Colorado","Condor","Constantina","Coqueiro Baixo","Coqueiros do Sul",
    "Coronel Barros","Coronel Bicaco","Coronel Pilar","Cotiporã","Coxilha",
    "Crissiumal","Cristal","Cristal do Sul","Cruz Alta","Cruzaltense",
    "Cruzeiro do Sul","David Canabrava","Derrubadas","Dezesseis de Novembro",
    "Dionísio Cerqueira","Dona Francisca","Doutor Ricardo","Dumont","Eldorado do Sul",
    "Encantado","Encruzilhada do Sul","Engenho Velho","Entre Rios do Sul",
    "Entre-Ijuís","Erebango","Erechim","Erval Grande","Erval Seco","Esmeralda",
    "Esperança do Sul","Espumoso","Estação","Estância Velha","Esteio",
    "Estrela","Estrela Velha","Farroupilha","Faxinal do Soturno","Faxinalzinho",
    "Fazenda Vilanova","Feliz","Flores da Cunha","Floresta","Floriano Peixoto",
    "Fontoura Xavier","Formigueiro","Forquetinha","Fortaleza dos Valos","Frederico Westphalen",
    "Garibaldi","Garibaldina","Garruchos","Gaurama","General Câmara","Gentil",
    "Getúlio Vargas","Giruá","Glorinha","Gramado","Gramado dos Loureiros",
    "Gramado Xavier","Gravataí","Guabiju","Guaíba","Guaporé","Guarani das Missões",
    "Guarujá do Sul","Guatambú","Herval","Herveiras","Horizontina","Hulha Negra",
    "Humaitá","Ibarama","Ibiaçá","Ibiraiaras","Ibirapuitã","Ibirubá",
    "Igrejinha","Ijuí","Ilópolis","Imbé","Imigrante","Independência",
    "Ipiranga do Sul","Itaara","Itacurubi","Itaqui","Itati","Itatiba do Sul",
    "Ivati","Ivotim","Jaboticaba","Jacutinga","Jaguarão","Jaguari",
    "Jaguaruna","Jari","Jóia","José de Alencar","Juá","Júlio de Castilhos",
    "Lagoa Bonita do Sul","Lagoa do Três Cantos","Lagoa Vermelha","Lajeado",
    "Lavras do Sul","Liberato Salzano","Lindolfo Collor","Linha Nova",
    "Maçambará","Machadinho","Mampituba","Manoel Viana","Maquiné","Maratá",
    "Marcelino Ramos","Mariana Pimentel","Mariano Moro","Marques de Souza",
    "Mata","Mato Castelhano","Mato Leitão","Mato Queimado","Maximiliano de Almeida",
    "Minas do Leão","Miraguaí","Montauri","Monte Alegre dos Campos",
    "Monte Belo do Sul","Montenegro","Mormaço","Morrinhos do Sul","Morro Reuter",
    "Mostardas","Muçum","Muito Novo do Norte","Nonoai","Nova Alvorada",
    "Nova Araçá","Nova Bassano","Nova Boa Vista","Nova Bréscia","Nova Escócia",
    "Nova Pádua","Nova Prata","Nova Ramada","Nova Roma do Sul","Nova Santa Rita",
    "Novo Barreiro","Novo Cabrais","Novo Hamburgo","Novo Machado","Novo Tiradentes",
    "Osório","Paim Filho","Palmares do Sul","Palmeira das Missões","Palmitinho",
    "Panambi","Pantano Grande","Parai","Paraíso do Sul","Pareci Novo",
    "Parobé","Passa Sete","Passo do Sobrado","Passo Fundo","Paulo Bento",
    "Paverama","Pedras Altas","Pedro Osório","Pejuçara","Pelotas",
    "Picada Café","Pinhal","Pinhal da Serra","Pinhal Grande","Pinheirinho do Vale",
    "Pinto Bandeira","Pirapó","Piratini","Planalto","Poço das Antas",
    "Pontão","Portão","Porto Alegre","Porto Lucena","Porto Mauá",
    "Porto Vera Cruz","Porto Xavier","Pouso Novo","Presidente Epitácio",
    "Presidente Prudente","Putinga","Quaraí","Quatro Irmãos","Quevedos",
    "Quinze de Novembro","Redentora","Relvado","Restinga Seca","Rio Branco",
    "Rio Grande","Rio Pardo","Rio dos Índios","Riozinho","Roca Sales",
    "Rodeio Bonito","Rolante","Ronda Alta","Rondinha","Roque Gonzales",
    "Rosário do Sul","Sagrada Família","Saldanha Marinho","Salto do Jacuí",
    "Salvador do Sul","Sananduva","Sant'Ana do Livramento","Santa Bárbara do Sul",
    "Santa Cecília do Sul","Santa Clara do Sul","Santa Cruz do Sul",
    "Santa Margarida do Sul","Santa Maria","Santa Maria do Herval",
    "Santa Rosa","Santa Rosa do Sul","Santa Tereza","Santa Terezinha",
    "Santiago","Santo Ângelo","Santo Antônio da Patrulha","Santo Antônio das Missões",
    "Santo Antônio do Palma","Santo Antônio do Planalto","Santo Augusto",
    "Santo Cristo","Santo Expedito do Sul","São Borja","São Domingos do Sul",
    "São Francisco de Assis","São Francisco de Paula","São Gabriel",
    "São Jerônimo","São João da Urtiga","São João do Polêsine","São Jorge",
    "São José das Missões","São José do Herval","São José do Hortêncio",
    "São José do Inhacorá","São José do Norte","São José do Ouro","São José do Sul",
    "São José dos Ausentes","São Leopoldo","São Lourenço do Sul",
    "São Luiz Gonzaga","São Marcos","São Martinho","São Martinho da Serra",
    "São Miguel das Missões","São Nicolau","São Paulo do Sul","São Pedro da Aldeia",
    "São Pedro do Butiá","São Pedro do Sul","São Sebastião do Caí",
    "São Sepé","São Valentim","São Valentim do Sul","São Vicente do Sul",
    "Sapiranga","Sapucaia do Sul","Sarandi","Seberi","Sede Nova",
    "Segredo","Selbach","Senador Salgado Filho","Sentinela do Sul",
    "Serafina Corrêa","Sério","Sertão","Sertão Santana","Sete de Setembro",
    "Severiano de Almeida","Silveira Martins","Sinimbu","Sobradinho",
    "Soledade","Tabaí","Tapejara","Tapera","Tapetes","Taquara",
    "Taquari","Taquaruçu do Sul","Tavares","Tenente Portela","Terra de Areia",
    "Teutônia","Tiradentes do Sul","Toropi","Tramandaí","Travesseiro",
    "Três Arroios","Três Cachoeiras","Três Coroas","Três de Maio",
    "Três Forquilhas","Três Palmeiras","Três Passos","Trindade do Sul",
    "Triunfo","Tucunduva","Tunas","Tupanci do Sul","Tupanciretã",
    "Tupandi","Tuparendi","Turuçu","Ubiretama","União da Serra",
    "Unistalda","Uruguaiana","Vacaria","Vale do Sol","Vale Real",
    "Vale Verde","Vanini","Venâncio Aires","Vera Cruz","Veranópolis",
    "Vespasiano Corrêa","Viadutos","Viamão","Vicente Dutra","Victor Graeff",
    "Vila Flores","Vila Lângaro","Vila Maria","Vila Nova do Sul","Vista Alegre",
    "Vista Alegre do Prata","Vista Gaúcha","Vitória das Missões","Westfália",
    "Xangri-lá"
  ],
  RO: [
    "Alta Floresta do Oeste","Alto Alegre do Parecis","Alto Paraíso","Ariquemes",
    "Buritis","Cacoal","Cacaulândia","Campo Novo de Rondônia","Candeias do Jamari",
    "Castanheiras","Cerejeiras","Chupinguaia","Colorado do Oeste","Corumbiara",
    "Costa Marques","Cujubim","Espigão d'Oeste","Guajará-Mirim","Itapuã do Oeste",
    "Jaru","Ji-Paraná","Machadinho d'Oeste","Ministro Andreazza","Mirante da Serra",
    "Nova Brasilândia d'Oeste","Nova Mamoré","Nova União","Ouro Preto do Oeste",
    "Pimenta Bueno","Pimenteiras do Oeste","Porto Velho","Presidente Médici",
    "Primavera de Rondônia","Quixiá","Rio Crespo","Rolim de Moura","Santa Luzia d'Oeste",
    "São Felipe d'Oeste","São Francisco do Guaporé","São Miguel do Guaporé",
    "Seringueiras","Teixeirópolis","Theobroma","Urupá","Vale do Anari",
    "Vale do Paraíso","Vilhena","Vista Alegre do Abunã"
  ],
  SC: [
    "Abdon Batista","Abelardo Luz","Agrolândia","Agronômica","Água Doce",
    "Águas de Chapecó","Águas Frias","Águas Mornas","Alfredo Wagner","Alto Bela Vista",
    "Anchieta","Angelina","Anita Garibaldi","Anitápolis","Antônio Carlos",
    "Araranguá","Arroio Trinta","Arvoredo","Ascurra","Atalanta","Aurora",
    "Balneário Arroio do Silva","Balneário Barra do Sul","Balneário Camboriú",
    "Balneário Gaúcha","Balneário Piçarras","Balneário Rincão","Bandeirante",
    "Barra Bonita","Barra Velha","Bela Vista do Toldo","Belmonte","Benedito Novo",
    "Biguaçu","Blumenau","Bocaína do Sul","Bom Jardim da Serra","Bom Jesus",
    "Bom Jesus do Oeste","Bom Retiro","Bombinhas","Botuverá","Braço do Norte",
    "Braço do Trombudo","Brunópolis","Brusque","Caçador","Caibi","Calmon",
    "Camboriú","Capão Alto","Capinzal","Catanduvas","Caxambu do Sul",
    "Celso Ramos","Cerro Negro","Chapadão do Lageado","Chapéu do Sul",
    "Concórdia","Cordilheira do Norte","Coronel Freitas","Coronel Martins",
    "Correia Pinto","Criciúma","Cunha Porã","Cunhataí","Curitibanos",
    "Dionísio Cerqueira","Doutor Pedrinho","Erval Velho","Faxinal dos Guedes",
    "Florianópolis","Formosa do Sul","Forquilhinha","Fraiburgo","Frei Rogério",
    "Galvão","Garopaba","Garuva","Gaspar","Governador Celso Ramos",
    "Grão Pará","Gravatal","Guabiruba","Guaporá","Guarujá do Sul",
    "Guatambú","Herval d'Oeste","Ibiam","Ibicaré","Ibiconde",
    "Ibirité","Içara","Ilhota","Imaruí","Imbituba","Imbuia",
    "Indaial","Ipira","Ipumirim","Irani","Itá","Itaiópolis",
    "Itajaí","Itapema","Itapiranga","Itapirú","Itapuí","Ituporanga",
    "Jaborá","Jacinto Machado","Jaraguá do Sul","Jardinópolis","Joaçaba",
    "Joinville","José Boiteux","Jupiá","Lacerdópolis","Lages",
    "Laguna","Laurentino","Lauro Müller","Lebon Régis","Leoberto Leal",
    "Lindóia do Sul","Lontras","Luiz Alves","Luzerna","Macieira",
    "Mafra","Major Gercino","Major Vieira","Maracajá","Maravilha",
    "Marema","Massaranduba","Matos Costa","Meleiro","Mirim Doce",
    "Modelo","Mondaí","Monte Carlo","Monte Castelo","Morro da Fumaça",
    "Morro Grande","Navegantes","Nova Erechim","Nova Itaberaba","Nova Trento",
    "Nova Veneza","Novo Horizonte","Orleans","Otacílio Costa","Ouro",
    "Ouro Velho","Palhoça","Palma Sosa","Palmeira","Palmitos",
    "Papanduva","Passo de Torres","Passos Maia","Paulo Lopes","Pedras Grandes",
    "Penha","Peritiba","Petrolândia","Pinhalzinho","Pintadas",
    "Piratuba","Planalto Alegre","Pomerode","Ponte Alta","Ponte Alta do Norte",
    "Ponte Serrada","Porto Belo","Porto União","Posse do Paraná","Pouso Redondo",
    "Praia Grande","Princesa","Rancho Queimado","Rio das Antas","Rio do Campo",
    "Rio do Oeste","Rio do Sul","Rio dos Cedros","Rio Fortuna","Rio Negrinho",
    "Rodeio","Romelândia","Sangão","Santa Cecília","Santa Helena",
    "Santa Rosa de Lima","Santo Amaro da Imperatriz","São Bento do Sul",
    "São Bernardino","São Bonifácio","São Francisco do Sul","São João Batista",
    "São João do Itaperiú","São João do Oeste","São João do Sul","São Joaquim",
    "São José","São Lourenço do Oeste","São Ludgero","São Pedro de Alcântara",
    "Schroeder","Siderópolis","Sombrio","Taio","Tigrinhos","Tijucas",
    "Timbé do Sul","Timbó","Treze de Maio","Treze Tílias","Trombudo Central",
    "Tubarão","Turvo","Urussanga","Vidal Ramos","Vitor Meireles",
    "Witmarsum"
  ],
  SE: [
    "Amparo de São Francisco","Aquidabã","Aracaju","Arauá","Boquim",
    "Brejo Grande","Campo do Brito","Canhoba","Canindé de São Francisco",
    "Capela","Carira","Carmópolis","Cedro de São João","Cristinápolis",
    "Cumbe","Divina Pastora","Estância","Feira Nova","Frei Paulo",
    "Gararu","Gracho Cardoso","Ilha das Flores","Indiaroba","Itabaiana",
    "Itabaianinha","Itaporanga d'Ajuda","Japaratuba","Japoatã",
    "Lagarto","Laranjeiras","Macambira","Malhada dos Bois","Malhador",
    "Maruim","Moita Bonita","Monte Alegre de Sergipe","Muribeca",
    "Neópolis","Nossa Senhora Aparecida","Nossa Senhora da Glória",
    "Nossa Senhora das Dores","Nossa Senhora de Lourdes","Nossa Senhora do Socorro",
    "Pacatuba","Pambu","Penedo","Piaçabuçu","Pilar",
    "Riachão do Dantas","Riachuelo","Ribeirópolis","Rosário do Catete",
    "Salgado","Santa Luzia do Itanhy","Santa Rosa de Lima","Santo Amaro das Brotas",
    "São Cristóvão","São Domingos","São Francisco","São José da Varginha",
    "São Miguel do Aleixo","Simão Dias","Siriri","Tabira","Telha",
    "Tobias Barreto","Tomar do Geru","Umbaúba"
  ],
  SP: [
    "Adamantina","Adolfo","Aguaí","Águas da Prata","Águas de Lindóia",
    "Águas de Santa Bárbara","Águas de São Pedro","Agudos","Alambari","Albertina",
    "Alfredo Marcondes","Altair","Alto Alegre","Alto Feliz","Álvares Florence",
    "Álvares Machado","Álvaro de Carvalho","Alvinlândia","Americana","Américo de Campos",
    "Amparo","Analândia","Andradina","Angatuba","Anhembi","Anhumas",
    "Aparecida","Aparecida d'Oeste","Apiaí","Apiaí","Aracariguama","Aracatuba",
    "Aracoiaba da Serra","Aramina","Arandu","Araçatuba","Araraquara","Araras",
    "Araçoiaba da Serra","Arco-Íris","Arealva","Areias","Areiópolis","Ariranha",
    "Artur Nogueira","Arujá","Aspasia","Assis","Atibaia","Auriflama",
    "Avaí","Avanhandava","Avaré","Bady Bassitt","Balbinos","Bálsamo",
    "Bananal","Barão de Antonina","Barbosa","Bariri","Barra Bonita","Barra do Chapéu",
    "Barra do Turvo","Barretos","Barrinha","Barueri","Bastos","Batatais",
    "Bauru","Bebedouro","Bento de Abreu","Bernardino de Campos","Bertioga",
    "Bilac","Birigui","Biritiba-Mirim","Boa Esperança do Sul","Boa Vista do Tapuã",
    "Bocaina","Bofete","Boituva","Bom Jesus dos Perdões","Bom Sucesso de Itararé",
    "Borá","Boracéia","Borboleta","Bom Retiro","Botucatu","Bragança",
    "Bragança Paulista","Braúna","Brejo Alegre","Brotas","Buri","Buritama",
    "Buritizal","Cabrália Paulista","Cabrero","Cachoeira Paulista","Caconde",
    "Cafelândia","Caiabu","Caieiras","Cajamar","Cajati","Cajuru",
    "Campinas","Campo do Meio","Campina Verde","Campos do Jordão","Campos Novos Paulistas",
    "Cananéia","Canas","Cândido Mota","Cândido Rodrigues","Canitar","Capão Bonito",
    "Capela do Alto","Capivari","Caraguatatuba","Carapicuíba","Cardoso",
    "Casa Branca","Cássia dos Coqueiros","Cássia","Castilho","Catanduva",
    "Catiguá","Cedral","Cerqueira César","Cerquilho","Cesário Lange",
    "Charqueada","Clementino","Colina","Colômbia","Conchal","Conchas",
    "Cordeirópolis","Coroados","Coronel Macedo","Corumbataí","Cosmópolis",
    "Cosmorama","Cotia","Cravinhos","Cristais Paulista","Cruzália",
    "Cruzeiro","Cruz das Almas","Cubatão","Cunha","Descalvado","Diadema",
    "Dirce Reis","Divinolândia","Dobrada","Dois Córregos","Dolcinópolis",
    "Dourado","Dracena","Duartina","Dumont","Echaporã","Eldorado",
    "Elisiário","Embaúba","Embu das Artes","Embu-Guaçu","Emiliano Ramos",
    "Engenheiro Coelho","Espírito Santo do Pinhal","Espírito Santo do Turvo",
    "Estrela do Norte","Estrela d'Oeste","Fartura","Fernando Prestes","Fernandópolis",
    "Fernão","Ferraz de Vasconcos","Flora Rica","Florínia","Floresta Azul",
    "Florida Paulista","Franca","Francisco Morato","Franco da Rocha",
    "Gabriel Monteiro","Garça","Gavião Peixoto","General Salgado","Glicério",
    "Guapiaçu","Guapiaçu","Guaratinguetá","Guarujá","Guarulhos","Guará",
    "Guarani d'Oeste","Guarani Paulista","Guaricanga","Herculândia","Holambra",
    "Herculândia","Iacanga","Iacri","Ibaté","Ibiraçu","Ibitinga",
    "Ibitiúra de Minas","Ibituruna","Igaraçu do Tietê","Iguape","Ilhabela",
    "Indaiatuba","Indiana","Ipaussu","Iporanga","Itaberá","Itaí",
    "Itajobi","Itaju","Itajú","Itanhaém","Itaóca","Itapecerica da Serra",
    "Itapetinga","Itapetininga","Itapeva","Itapevi","Itapirapuã Paulista",
    "Itápolis","Itaporanga","Itapuí","Itaúna","Itatinga","Itirapuã",
    "Itu","Itupeva","Ituverava","Jaborandi","Jaboticabal","Jacareí",
    "Jaci","Jacupiranga","Jaguariúna","Jales","Jambeiro","Jandaia do Sul",
    "Jardinópolis","Jarinu","Jaú","Joanópolis","João Ramalho","José Bonifácio",
    "Júlio Mesquita","Jumirim","Jundiaí","Junqueirópolis","Jururuí","Lavrinhas",
    "Leme","Lençóis Paulista","Limeira","Lins","Lorena","Lourdes",
    "Louveira","Lucélia","Lucianópolis","Lúcio Costa","Luís Antônio",
    "Lupércio","Marília","Mairinque","Mairiporã","Marabá Paulista","Maracaí",
    "Marapoama","Marinópolis","Marília","Martinópolis","Matão","Mauá",
    "Mendonça","Meridiano","Mesópolis","Miguelópolis","Mineiros do Tietê",
    "Mira Estrela","Miracatu","Mirandópolis","Mirassol","Mirassolândia",
    "Mogi Guaçu","Mogi Mirim","Monções","Mongaguá","Monte Alegre do Sul",
    "Monte Alto","Monte Aprazível","Monte Azul Paulista","Monteiro Lobato",
    "Monte Mor","Morro Agudo","Morungaba","Motuca","Nazaré Paulista",
    "Neves Paulista","Nhandeara","Nipoã","Nova Aliança","Nova Campina",
    "Nova Canaã Paulista","Nova Castilho","Nova Europa","Nova Granada",
    "Nova Guataporanga","Nova Independência","Novo Horizonte","Nuporanga",
    "Ocauçu","Olímpia","Onda Verde","Oriente","Orindiúva","Orlândia",
    "Ourinhos","Ouroeste","Ouro Verde","Pacaembu","Palestina","Palmares Paulista",
    "Palmeira d'Oeste","Palmital","Panorama","Paraibuna","Paraíso",
    "Paranapanema","Paranapuã","Parapuã","Pardinho","Pariquera-Açu",
    "Pariquera-Açu","Park City","Patrocínio Paulista","Paulicéia","Paulínia",
    "Paulo de Faria","Paulo Finski","Pedra Bela","Pedranópolis","Pedregulho",
    "Pedreira","Pedro de Toledo","Penápolis","Pereira Barreto","Pereiras",
    "Peruíbe","Piacatu","Piedade","Pilar do Sul","Pindamonhangaba",
    "Pindorama","Pinhalzinho","Piquerobi","Piquete","Piracaí","Piracicaba",
    "Pirapora do Bom Jesus","Pirapozinho","Pirassununga","Piratininga","Platina",
    "Poloni","Pompéia","Porangaba","Pratânia","Presidente Epitácio",
    "Presidente Prudente","Presidente Venceslau","Quatá","Queluz",
    "Rafael","Regente Feijó","Regis Bittencourt","Restinga","Ribeirão Bonito",
    "Ribeirão Preto","Ribeirão Preto","Rifaina","Rincão","Riolândia",
    "Rivera","Roosevelt","Rosana","Roseira","Rubião Júnior","Sandovalina",
    "Santa Adélia","Santa Albertina","Santa Bárbara d'Oeste","Santa Branca",
    "Santa Clara d'Oeste","Santa Cruz da Esperança","Santa Cruz das Palmeiras",
    "Santa Cruz do Rio Pardo","Santa Ernestina","Santa Fé do Sul",
    "Santa Gertrudes","Santa Helena de Goiás","Santa Helena","Isaac",
    "Santa Lúcia","Santa Maria da Serra","Santa Mercedes","Santa Rita d'Oeste",
    "Santa Rita do Passa Quatro","Santa Rita do Sapucaí","Santa Rosa de Viterbo",
    "Santa Salete","Santana da Ponte Pensa","Santana de Parnaíba",
    "Santo Anastácio","Santo André","Santo Antônio da Alegria","Santo Antonio de Posse",
    "Santo Antonio do Aracanguá","Santo Antonio do Jardim","Santo Antonio do Pinhal",
    "Santo Expedito","Santo Hipólito","Santos","São Bento do Sapucaí",
    "São Bernardo do Campo","São Caetano do Sul","São Carlos","São Francisco",
    "São Francisco Xavier","São Joaquim da Barra","São José do Barreiro",
    "São José do Rio Pardo","São José do Rio Preto","São José dos Campos",
    "São Lourenço da Serra","São Luís do Paraitinga","São Manuel",
    "São Miguel Arcanjo","São Paulo","São Pedro","São Pedro do Turvo",
    "São Roque","São Sebastião","São Sebastião da Grama","São Simão",
    "São Vicente","Sarapuí","Sarutaiá","Sebastianópolis do Sul","Serra Azul",
    "Serrana","Sertãozinho","Sete Barras","Severínia","Silveiras",
    "Socorro","Sorocaba","Sud Mennucci","Sumaré","Suzano","Suzanápolis",
    "Tabapuã","Tabatinga","Taboão da Serra","Tupã","Taubaté","Tejupá",
    "Timburi","Torre de Pedra","Três Fronteiras","Tupi Paulista","Ubatuba",
    "Urupês","Vargem Grande do Sul","Vargem Grande Paulista","Várzea Paulista",
    "Vinhedo","Viradouro","Vista Alegre do Alto","Votorantim","Votuporanga"
  ],
  TO: [
    "Abreulândia","Aguiar","Almas","Alvorada","Araguaína","Araguanã",
    "Araguatins","Arraias","Augustinópolis","Aurora do Tocantins","Axixá do Tocantins",
    "Babaçulândia","Bandeirantes do Tocantins","Barrolândia","Bernardo Sayão",
    "Boa Vista do Tocantins","Bom Jesus do Tocantins","Brasilândia do Tocantins",
    "Brejinho de Nazaré","Buriti do Tocantins","Cachoeirinha","Campos Lindos",
    "Cariri do Tocantins","Carmolândia","Carrasco Bonito","Caseara",
    "Centro Novo do Maranhão","Chapada da Natividade","Chapada de Areia",
    "Colinas do Tocantins","Colônia do Piauí","Conceição do Tocantins",
    "Couto Magalhães","Cristalândia","Crixás do Tocantins","Darcinópolis",
    "Dianópolis","Divinópolis do Tocantins","Dois Irmãs do Tocantins",
    "Duerê","Esperantina","Fátima","Figueirópolis","Filadélfia",
    "Fortaleza do Tabocão","Goianorte","Goiatins","Guaraí","Guarani",
    "Gurupi","Ipueiras","Itacajá","Itaguatins","Itapiratins",
    "Itaporã do Tocantins","Jaú do Tocantins","Juarina","Lagoa da Confusão",
    "Lagoa do Tocantins","Lavandeira","Lizarda","Luzinópolis","Marianópolis do Tocantins",
    "Mauzinho do Tocantins","Miracema do Tocantins","Mirandópolis do Tocantins",
    "Miranorte","Monte do Carmo","Monte Lindo do Tocantins","Monte Santo do Tocantins",
    "Morro Cabeça no Tempo","Muricilândia","Natividade","Nazaré","Nova Olinda do Tocantins",
    "Nova Rosalândia","Novo Acordo","Novo Alegre","Novo Jardim","Oliveira de Fátima",
    "Palmas","Palmeirante","Palmeiras do Tocantins","Palmeirópolis","Paraíso do Tocantins",
    "Paranã","Pau D'Arco","Pedro Afonso","Peixe","Pequizeiro",
    "Pindorama do Tocantins","Piraquê","Pium","Ponte Alta do Bom Jesus",
    "Ponte Alta do Tocantins","Porto Alegre do Tocantins","Porto Nacional",
    "Praia Norte","Presidente Kennedy","Pugmil","Recursolândia","Riachinho",
    "Riacho do Ouro","Rio da Conceição","Rio dos Bois","Rio Sono","Sampaio",
    "Sandolândia","Santa Fé do Araguaia","Santa Maria do Tocantins",
    "Santa Rita do Tocantins","Santa Rosa do Tocantins","São Bento do Tocantins",
    "São Félix do Tocantins","São Miguel do Tocantins","São Salvador do Tocantins",
    "São Sebastião do Tocantins","Silvanópolis","Sítio Novo do Tocantins",
    "Sul Novo","Tocantinópolis","Tupirama","Tupiratins","Wanderlândia","Xambioá"
  ]
};

export type UF = {
  sigla: string;
  nome: string;
};

/** 27 UFs do Brasil */
export const UFS: UF[] = [
  { sigla: 'AC', nome: 'Acre' },
  { sigla: 'AL', nome: 'Alagoas' },
  { sigla: 'AP', nome: 'Amapá' },
  { sigla: 'AM', nome: 'Amazonas' },
  { sigla: 'BA', nome: 'Bahia' },
  { sigla: 'CE', nome: 'Ceará' },
  { sigla: 'DF', nome: 'Distrito Federal' },
  { sigla: 'ES', nome: 'Espírito Santo' },
  { sigla: 'GO', nome: 'Goiás' },
  { sigla: 'MA', nome: 'Maranhão' },
  { sigla: 'MT', nome: 'Mato Grosso' },
  { sigla: 'MS', nome: 'Mato Grosso do Sul' },
  { sigla: 'MG', nome: 'Minas Gerais' },
  { sigla: 'PA', nome: 'Pará' },
  { sigla: 'PB', nome: 'Paraíba' },
  { sigla: 'PR', nome: 'Paraná' },
  { sigla: 'PE', nome: 'Pernambuco' },
  { sigla: 'PI', nome: 'Piauí' },
  { sigla: 'RJ', nome: 'Rio de Janeiro' },
  { sigla: 'RN', nome: 'Rio Grande do Norte' },
  { sigla: 'RS', nome: 'Rio Grande do Sul' },
  { sigla: 'RO', nome: 'Rondônia' },
  { sigla: 'RR', nome: 'Roraima' },
  { sigla: 'SC', nome: 'Santa Catarina' },
  { sigla: 'SE', nome: 'Sergipe' },
  { sigla: 'SP', nome: 'São Paulo' },
  { sigla: 'TO', nome: 'Tocantins' }
];

export const PAISES = [
  { value: 'Brasil', label: 'Brasil' },
  { value: 'Estados Unidos', label: 'Estados Unidos' },
  { value: 'Portugal', label: 'Portugal' },
  { value: 'Argentina', label: 'Argentina' },
  { value: 'Colômbia', label: 'Colômbia' },
  { value: 'Chile', label: 'Chile' },
  { value: 'México', label: 'México' },
  { value: 'Reino Unido', label: 'Reino Unido' },
  { value: 'Alemanha', label: 'Alemanha' },
  { value: 'Espanha', label: 'Espanha' },
  { value: 'França', label: 'França' },
  { value: 'Canadá', label: 'Canadá' },
  { value: 'Austrália', label: 'Austrália' },
  { value: 'Japão', label: 'Japão' },
  { value: 'China', label: 'China' },
  { value: 'Outro', label: 'Outro' }
];
